# version = "0.1.6"
text:
  # RGB colour for text
  red: 170
  green: 43
  blue: 255

back:
  # RGB colour for shadow or outline
  red: 0
  green: 0
  blue: 0

highlight:
  # Type of highlight
  # 0 = none
  # 1 = outline
  # 2 = shadow
  type: 1
  
display:
  # Whether to leave last payed on display when stopped, or
  # display splash screen
  # 0 = leave last played
  # 1 = display splash
  splash: 1
  
